### ISSUE TITLE
The current latest version, 2.0.6, broken

### ISSUE THREAD

**Issue by AKK9** [LambdaTest/testcafe-browser-provider-lambdatest#18]
The current published version on npm is 2.0.6. I may be mistaken, but as far as I can tell this package contains no `lib` directory.

**Comment by dubesar** [comment]
Hello @AKK9, we are working on the broken 2.0.6 version. Also, the lib folder is created after building the package. Sorry for the delay, will be soon back with a solution.

**Comment by dubesar** [comment]
@AKK9 a new version is up.
