### ISSUE TITLE
URL in browser after tests launch.

### ISSUE THREAD

**Issue by Sairef** [LambdaTest/testcafe-browser-provider-lambdatest#2]
Hi! I have used steps from Readme. 
my script is  "LT_USERNAME=*** LT_ACCESS_KEY=*** testcafe" (list of fixtures is in config file)
After I start the test, all I got is this. 

![d2c3cddc9d](https://user-images.githubusercontent.com/23234835/63654359-ffede480-c781-11e9-9fc6-6e48a629dafd.jpg)

Can you give me an advice, what am I missing?

**Comment by kanhaiya15** [comment]
Hi @WildMav , 
I have tried to replicate the same, However, it'll working fine for me.
Could you please share a sample code along with CLI command that you used to run the Fixtures.

**Comment by weyert** [comment]
I have the same issue and I am using the following command in the shell

`LT_USERNAME=xxx LT_ACCESS_KEY=xx LT_VERBOSE=true LT_ENABLE_TRACE=true DEFAULT_USERNAME="xxx" DEFAULT_PASSWORD="yyy" ./node_modules/.bin/testcafe "lambdatest:Safari`

**Comment by 4DvAnCeBoY** [comment]
> Hi! I have used steps from Readme.
> my script is "LT_USERNAME=*** LT_ACCESS_KEY=*** testcafe" (list of fixtures is in config file)
> After I start the test, all I got is this.
> 
> ![d2c3cddc9d](https://user-images.githubusercontent.com/23234835/63654359-ffede480-c781-11e9-9fc6-6e48a629dafd.jpg)
> 
> Can you give me an advice, what am I missing?

@Sairef: This might be the case of network policy or the firewall restriction, which are blocking the tunnel to route the traffic through TestCafe Proxy.

Here is the troubleshooting guide for the tunnel.
https://www.lambdatest.com/support/docs/troubleshooting-lambda-tunnel/

**Comment by 4DvAnCeBoY** [comment]
> I have the same issue and I am using the following command in the shell
> 
> `LT_USERNAME=xxx LT_ACCESS_KEY=xx LT_VERBOSE=true LT_ENABLE_TRACE=true DEFAULT_USERNAME="xxx" DEFAULT_PASSWORD="yyy" ./node_modules/.bin/testcafe "lambdatest:Safari`
> 
> Also when I give the browser it's starting a browser in Firefox on Windows which seems to be odd? Am I using the command wrong?

@weyert: The default mapping is not done for safari, however, you can use `testcafe -b lambdatest` to get list of acceptable browsers configuration.

You can get started with the sample https://github.com/LambdaTest/testcafe-sample
