### ISSUE TITLE
Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable

### ISSUE THREAD

**Issue by natkrish** [LambdaTest/testcafe-browser-provider-lambdatest#3]
I am getting this issue when running tests on LT using testcafe plugin. I have tried many options and it doesnt work. It works fine on desktop so I am sure its something to do with the tunnel. Can you please investigate
 1) Unhandled promise rejection:

      Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
      at ServerResponse.pipe (_http_outgoing.js:833:22)
      at respondOnWebSocket (C:\Users\krish.murthy\Documents\eh-qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib\request-pipel
      at Array.decideOnProcessingStrategy (C:\Users\krish.murthy\Documents\eh-qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib
      at run (C:\Users\krish.murthy\Documents\eh-qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:15
      at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by 4DvAnCeBoY** [comment]
@natkrish, We have fixed the issue in the recent release. Please share the tunnelLog file, if the issue still persists.

**Comment by nkrishna79** [comment]
@4DvAnCeBoY  - I dont think this is fixed. Can you please take a look at the tunnellog and also my output from test cafe. If you need any more info please do ask. 

![image](https://user-images.githubusercontent.com/37705580/69139331-35237d80-0ab8-11ea-9773-4ab09f361dc5.png)

Thanks
Krish 
[lambdaTunnelLog.log](https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/files/3863280/lambdaTunnelLog.log)

**Comment by nikhil-lambda** [comment]
Hi @natkrish 

Thanks for sharing the tunnel logs. My team is already on it. For detail information we will reach out to you. So we can help you with this as soon as possible.  I appericate your help for bringing this up in our notice.

**Comment by nikhil-lambda** [comment]
Hi @natkrish,

As we discussed it something related to frame blocking.  Please see this issue already open on testCafe hammerhead thread. 

https://github.com/DevExpress/testcafe-hammerhead/issues/47

https://github.com/DevExpress/testcafe-hammerhead/issues/114

**Comment by nkrishna79** [comment]
@nikhil-lambda 
I found out a way to overcome the issue that happened at the end of the test run. I just pass the flag --skip-js-errors and it works fine without any issues . I am happy to close this ticket. Thanks for your help

**Comment by nimovvk2803** [comment]
i''m facing exactly the same issue, and the resolution provided dint work. (--skip-js-errors).
please help
