### ISSUE TITLE
Errors in local machine and CI servers after upgrading to version 2.0.18

### ISSUE THREAD

**Issue by sduduzog** [LambdaTest/testcafe-browser-provider-lambdatest#31]
![image](https://user-images.githubusercontent.com/48126337/155505584-bc548bbf-35e1-4246-999b-2c2e3b45d922.png)

**Comment by dubesar** [comment]
Hello @sduduzog thanks for reporting this issue, I guess this issue is related to node-tunnel and not testcafe-browser-provider as specific. We will be fixing this is.
