### ISSUE TITLE
browserVersion errors on 2.0.25 and 2.0.26

### ISSUE THREAD

**Issue by AKK9** [LambdaTest/testcafe-browser-provider-lambdatest#47]
We're noticing the following error when using version 2.0.25 or 2.0.26:
```bash
GeneralError: Unable to open the "lambdatest:chrome" browser due to the following error:
Error: TypeError: Cannot read properties of undefined (reading 'browserVersion')
```

We have tried chrome and firefox. The same problem occurs.

Our workaround is to stick with 2.0.24 for the time being.

**Comment by Shivanshu-lambdatest** [comment]
Thanks @DanielHaroldLane for opening the issue & feedback, we will work on it.

**Comment by DanielHaroldLane** [comment]
FYI, thanks for merging these changes. If you folks could release to npm that'd be amazing :+1:

**Comment by Shivanshu-lambdatest** [comment]
@DanielHaroldLane new version published
