### ISSUE TITLE
Check if `src/httpserver.js` needs to be deleted or not

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/testcafe-browser-provider-lambdatest#55]
This file [`src/httpserver.js`](https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/blob/master/src/httpserver.js) whole file code is commented.

It has to checked if this file can safely removed or not.

**Comment by vickywane** [comment]
I cloned the project and took a look at this. 

Can I be assigned the issue? 

@Delta456 @navin772

**Comment by vickywane** [comment]
@Delta456 @navin772 I have opened #63  PR to remove this unused file.
