### ISSUE TITLE
Add documentation for each function

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/testcafe-browser-provider-lambdatest#56]
None of the functions used in the project have documentation. The functions need to be documented so that it is easier for users to understand how the code is working.

[Inline Documentation Standard](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/) will be a good starting point on how to write documentation.

**Comment by vickywane** [comment]
Hi @navin772 @Delta456 

I'd love to work on this issue.

**Comment by blissbug** [comment]
Hey! I would like to work on it!

**Comment by navin772** [comment]
@vickywane are you working on this? We haven't received any updates or PR from you. If you are not working on it, please unassign yourself.

**Comment by vickywane** [comment]
Hi @navin772 

I;m still working on this and I'll have a PR up soon.
