### ISSUE TITLE
Check and update dependencies to the latest version

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/testcafe-browser-provider-lambdatest#57]
The dependencies in `package.json` might be outdated and need to be updated. Check if the project still works after updating dependencies to their latest version.

**Comment by parthib2004** [comment]
I can do it! Please assign these to me.

**Comment by Delta456** [comment]
Go ahead and work on the issue.

**Comment by Yash-sudo-web** [comment]
@parthib2004 , are you still working on this issue or can i pick it up?

**Comment by parthib2004** [comment]
> @parthib2004 , are you still working on this issue or can i pick it up?

yeah go ahead, I am currently having some issues.

**Comment by Yash-sudo-web** [comment]
@Delta456 can you assign this to me then?

**Comment by vickywane** [comment]
@Delta456 seems no one is working actively on this. 

Can I take it up?
