### ISSUE TITLE
make GitHub Actions working again

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/testcafe-browser-provider-lambdatest#58]
GitHub Action must be working on each commit. 

The workflow file is located in `.github/workflows/main.yml` which doesn't work.

This file can serve as a starting point to make GitHub Actions to be working again.

**Comment by Yash-sudo-web** [comment]
can i work on this issue?

**Comment by Delta456** [comment]
@Yash-sudo-web someone else has taken it. Check the PR and see if you can review and help with it. 

Hopefully we will be opening more issues.

**Comment by Abhishek332** [comment]
@Delta456 I added a suggestion in PR, please have a look.
I am also looking to contribute, looking forward to see more open issues😃
